/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package structures;

public class App {
    public static void main(String[] args) {
        Lista myList = new Lista(3);

        Lista variada = new Lista(1,2,3,4);

        myList.print();
    }
}
